//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.GI.hypermart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilePlatform
    {
        public int Files_ID { get; set; }
        public string Platforms_ID { get; set; }
    
        public virtual Platform Platform { get; set; }
        public virtual File File { get; set; }
    }
}
