//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.GI.hypermart.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Open.GI.hypermart.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-apple.
        /// </summary>
        internal static string Apple {
            get {
                return ResourceManager.GetString("Apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download1 {
            get {
                object obj = ResourceManager.GetObject("Download1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download2 {
            get {
                object obj = ResourceManager.GetObject("Download2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download3 {
            get {
                object obj = ResourceManager.GetObject("download3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageNotFound {
            get {
                object obj = ResourceManager.GetObject("ImageNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-linux.
        /// </summary>
        internal static string Linux {
            get {
                return ResourceManager.GetString("Linux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-linux.
        /// </summary>
        internal static string Linux32 {
            get {
                return ResourceManager.GetString("Linux32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-linux.
        /// </summary>
        internal static string Linux64 {
            get {
                return ResourceManager.GetString("Linux64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoScreenShot {
            get {
                object obj = ResourceManager.GetObject("NoScreenShot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-windows.
        /// </summary>
        internal static string Win_10_32 {
            get {
                return ResourceManager.GetString("Win_10_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-windows.
        /// </summary>
        internal static string Win_10_64 {
            get {
                return ResourceManager.GetString("Win_10_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-windows.
        /// </summary>
        internal static string Win_32 {
            get {
                return ResourceManager.GetString("Win_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-windows.
        /// </summary>
        internal static string Win_64 {
            get {
                return ResourceManager.GetString("Win_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-windows.
        /// </summary>
        internal static string Win_8_32 {
            get {
                return ResourceManager.GetString("Win_8_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-windows.
        /// </summary>
        internal static string Win_8_64 {
            get {
                return ResourceManager.GetString("Win_8_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-windows.
        /// </summary>
        internal static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
    }
}
