var namespace_open_1_1_g_i_1_1hypermart_1_1_docs_1_1_data_transformation_objects =
[
    [ "ScreenShotDTO", "class_open_1_1_g_i_1_1hypermart_1_1_docs_1_1_data_transformation_objects_1_1_screen_shot_d_t_o.html", "class_open_1_1_g_i_1_1hypermart_1_1_docs_1_1_data_transformation_objects_1_1_screen_shot_d_t_o" ]
];