// <auto-generated />
namespace Open.GI.hypermart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRatings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRatings));
        
        string IMigrationMetadata.Id
        {
            get { return "201604062226321_AddRatings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
